
server:
  port: 8083

# Database and Application name Configurations  
spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: ratingservice
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  config:
    import: configserver:http://localhost:8085
        
    
    
## eureka Client Configurations  -> RATING-SERVICE
#eureka: 
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#      
#      
## Actuator Configurations  
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*" # Expose all endpoints
#  endpoint:
#    health:
#      show-details: always # Show full health details